### ISSUE TITLE
Trying to access flag --model_dir before flags were parsed error ./train.sh ssd_mobilenet_v1_egohands 

### ISSUE THREAD

**Issue by DilaraSina** [jkjung-avt/hand-detection-tutorial#10]
Hi, thanks for your tutorial. I have read the post and run the steps. At step 4 of Training section, I have run the command `./train.sh ssd_mobilenet_v1_egohands` and got titled error, which is also below in detail:

>   File "./models/research/object_detection/model_main.py", line 101, in <module>
    tf.app.run()
  File "/home/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "./models/research/object_detection/model_main.py", line 55, in main
    config = tf.estimator.RunConfig(model_dir=FLAGS.model_dir)
  File "/home/anaconda3/lib/python3.6/site-packages/absl/flags/_flagvalues.py", line 491, in __getattr__
    raise _exceptions.UnparsedFlagAccessError(error_message)
absl.flags._exceptions.UnparsedFlagAccessError: Trying to access flag --model_dir before flags were parsed.

How can I solve the problem?

**Comment by DilaraSina** [comment]
`./train.sh ssd_mobilenet_v2_egohands` has also yielded the same result

**Comment by DilaraSina** [comment]
what should I assign for model_dir?

**Comment by jkjung-avt** [comment]
Your problem looks very similar to the following.  Which version of tensorflow are you using?

https://github.com/tensorflow/models/issues/5239

**Comment by DilaraSina** [comment]
Thanks, I have reinstall the same version (1.10.0) and do not get the error.

Now I have other question, the training is performing currently (I guess, I run the command and terminal is still running).

Then I run these commands

> $ cd ~/project/hand-detection-tutorial
$ tensorboard --logdir=ssd_mobilenet_v1_egohands

Now at the browser (http://localhost:6006/) I got 

> No dashboards are active for the current data set.

Why this apperars? Does it matters?

**Comment by jkjung-avt** [comment]
When the model is being trained, you should see pretty high CPU/GPU usage.  Meanwhile, tensorboard should have worked.  Please check:

1. Do you have the same version of tensorboard as tensorflow installed on the system?  If not, try pip3 uninstall and re-install the proper version of tensorboard again.
2. You are training a 'ssd_mobilenet_v1_egohands' (not the other model), right?
