### ISSUE TITLE
Pretrained models for CPU

### ISSUE THREAD

**Issue by rutadesai** [jkjung-avt/hand-detection-tutorial#13]
Hi jkjung, 

Thanks for your work. I didn't see pretrained models on the repo. Would you be able to upload them? I want to just deploy them on CPU for some quick prototyping on videos. 

Thanks again!

**Comment by jkjung-avt** [comment]
The trained model files are rather large.  I have them stored on my desktop PC.  If you provide a location (say, Google Drive) for me to upload the files, I could send those files to you.  Please also specify which models you'd like to test with, e.g. 'ssd_mobilenet_v1_egohands', etc.

**Comment by rutadesai** [comment]
Thanks, I will send you a dropbox request on your gmail, if that is okay!

**Comment by Azazel17** [comment]
Same here, i really appreciate that pretrained models, can you provide them to me too please?

**Comment by jkjung-avt** [comment]
@rutadesai I've just uploaded the following trained model files to your Dropbox folder.  Hope it helps.

```
JK Jung - ssd_inception_v2_egohands.tar.gz
JK Jung - ssdlite_mobilenet_v2_egohands.tar.gz
JK Jung - faster_rcnn_inception_v2_egohands.tar.gz
JK Jung - ssd_mobilenet_v1_egohands.tar.gz
JK Jung - ssd_mobilenet_v2_egohands.tar.gz
```

**Comment by jkjung-avt** [comment]
@Azazel17 If you provide a place/link for me to upload the files, I could do that for you too.

**Comment by rutadesai** [comment]
Thank you!! Really appreciate your help!

**Comment by lxy5513** [comment]
@jkjung-avt  Hi, Could you please upload ssd_mobilenet_v2_egohands.tar.gz; ssd_mobilenet_v2_egohands.tar.gz file  to my dropbox ?  Thanks again! : )

**Comment by jkjung-avt** [comment]
@lxy5513 I've just uploaded the file for you.

**Comment by lxy5513** [comment]
Thank you, Appreciate for your kindness!

**Comment by guermal** [comment]
can you please send me also this models? or provide a direct link?

**Comment by jkjung-avt** [comment]
@guermal  I don't keep the trained models around any more...  It doesn't take much time to train the models by yourself using a decent GPU.
