### ISSUE TITLE
Detecting hand raised

### ISSUE THREAD

**Issue by iqrammm** [jkjung-avt/hand-detection-tutorial#16]
Hello there if I am interested to only detect hand that is raised for more than 2 seconds,is this algorithm possible?If yes which line should I adjust?

I did my research and I have found this pre-trained model :
https://download.01.org/opencv/2019/open_model_zoo/R1/20190404_140900_models_bin/person-detection-raisinghand-recognition-0001/FP16/

By my understanding, I can skip the training steps and use this model but by any chance do you know how to utilize them as I have trouble for a week now.

Hoping for your reply soon.

**Comment by jkjung-avt** [comment]
The pre-trained model in the link above is in Intel IR format.  It could only be used by OpenVINO.  If you plan to use the model on Intel x86 platforms (CPU only), then you could give it a try.

I think this question is not very relevant to the code in this repository, though.
