### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by gzz1529657064** [jkjung-avt/hand-detection-tutorial#19]
Thank you for your last reply. Your suggestions solvered my problem. I'm grateful to you very much!

I use MobileNet-YOLOv3 to train my own datasets(caffe model). Training is interrupted when testing the network.

I1021 10:17:16.232820 26936 solver.cpp:563] Iteration 1000, Testing net (#0)
I1021 10:17:16.232851 26936 net.cpp:679] Ignoring source layer label_data_1_split
I1021 10:17:16.239033 26936 net.cpp:679] Ignoring source layer Yolov3Loss1
I1021 10:17:16.239046 26936 net.cpp:679] Ignoring source layer Yolov3Loss2
I1021 10:17:16.239059 26936 net.cpp:679] Ignoring source layer Yolov3Loss3
*** Aborted at 1571624236 (unix time) try "date -d @1571624236" if you are using GNU date ***
PC: @     0x7fd3e047ea45 caffe::Blob<>::cpu_data()
*** SIGSEGV (@0x3a) received by PID 26936 (TID 0x7fd3e0db4b00) from PID 58; stack trace: ***
    @     0x7fd3deb804b0 (unknown)
    @     0x7fd3e047ea45 caffe::Blob<>::cpu_data()
    @     0x7fd3e04ae4db caffe::Solver<>::TestDetectionSeg()
    @     0x7fd3e04af5e9 caffe::Solver<>::TestAll()
    @     0x7fd3e04b50e0 caffe::Solver<>::Step()
    @     0x7fd3e04b531f caffe::Solver<>::Solve()
    @           0x40bf0c train()
    @           0x4087ce main
    @     0x7fd3deb6b830 __libc_start_main
    @           0x409029 _start
    @                0x0 (unknown)

I searched online, but I didn't find the answer.

**Comment by jkjung-avt** [comment]
Your caffe hits SIGSEGV (segmentation fault).  I guess it's because you've supplied bad data for testing.

Again, this question is not relevant to this repository at all.  Please do not abuse GitHub.
