### ISSUE TITLE
pre-trained hand detection models

### ISSUE THREAD

**Issue by MuhammadAsadJaved** [jkjung-avt/hand-detection-tutorial#21]
Hi sir, 
         Can you provide the pre-trained models for hand detection task? (you trained on egohands dataset) model that i can  run without retraining.

**Comment by jkjung-avt** [comment]
Yes.  Please provide a place (e.g. GoogleDrive) for me to upload the models.

**Comment by MuhammadAsadJaved** [comment]
Sir you can upload on Google Drive or Baidu pan and share link with me. I will download.

 No need to upload all , maybe you can upload just 2 (faster_rcnn_inception_v2_egohands  and ssd_inception_v2_egohands ) as we just want to make sure weather it is a problem with our faster_rcnn_inception_v2_boat model or with some libraries version to optimize and use our boat model. according to the demo on egohands dataset as mention in your tutorial https://jkjung-avt.github.io/tf-trt-models/

**Comment by jkjung-avt** [comment]
The models are too big for email.  I'm not going to put them on my own GoogleDrive.  Please provide a place for me to upload the files if you need them.

**Comment by MuhammadAsadJaved** [comment]
The link is sent to you in  the email sir.

**Comment by jkjung-avt** [comment]
Done uploading the 2 files.

**Comment by MuhammadAsadJaved** [comment]
Received sir. Thank you very much @jkjung-avt

**Comment by MuhammadAsadJaved** [comment]
If anyone needs these hand detection models, trained by @jkjung-avt , He sent me before. you can download it from here. 

https://drive.google.com/open?id=1WaqHP20Hy9nGunV87Wu6aEWrYiWcK_DP

**Comment by maky-hnou** [comment]
@MuhammadAsadJaved  and @jkjung-avt thank you for the upload, that saved a lot of time for us.

**Comment by miooooooooooo** [comment]
@MuhammadAsadJaved  the file has disappeared,  can you upload it again?Thank you.

**Comment by MuhammadAsadJaved** [comment]
@miooooooooooo   Hi, I am sorry I have removed models from the drive and I have tried to find in my system but unfortunately failed.  @maky-hnou  Can you please help him to upload models on the drive and share the link, please?

**Comment by maky-hnou** [comment]
Hello everyone, it has been long time ago since I used the models.  
I found some models in my computer, I hope they are the right ones.  
This is the [link](https://drive.google.com/drive/folders/16y8UmWabXbyCQy5-MUyVJZV58FC5yGs3?usp=sharing) on Google Drive.  
Please check it and tell me if it works or not.

**Comment by miooooooooooo** [comment]
@maky-hnou,this link is available!Thank you all so much.
