### ISSUE TITLE
evel config

### ISSUE THREAD

**Issue by PythonImageDeveloper** [jkjung-avt/hand-detection-tutorial#22]
Hi,
In the config file of models, in the eval section we have some options like:

> num_examples,
> max_evals

1- My validation dataset has 90k images, in your opinion, It's better to set num_examples = 90000 or smaller number? 
2- when I set to 90k, the evaluation recess become time-consuming.
And If I set to 10k, after each epoch finished and start to evaluation with 10k image, these 10k images for evaluation is done with which scenario?
* same?
* randomly choices?
*  if use 10k images for evaluation, then after 9 epoch one full evaluation is finished?

3- what's means max_evals?

**Comment by jkjung-avt** [comment]
1. An evaludation set of 90k images seems quite a lot.  I think you could reduce the number and move the remaining images to your training set.

2. I think what you are asking is not documented in tensorflow Object Detection API.  You'll have to read the source code to figure them out.  The relevant parts of the source code are:

   - [evaluator.py](https://github.com/tensorflow/models/blob/6518c1c7711ef1fdbe925b3c5c71e62910374e3e/research/object_detection/legacy/evaluator.py#L268)
   - [repeated_checkpoint_run() in eval_util.py](https://github.com/tensorflow/models/blob/6518c1c7711ef1fdbe925b3c5c71e62910374e3e/research/object_detection/eval_util.py#L334)
   - [_run_checkpoint_once() in eval_util.py](https://github.com/tensorflow/models/blob/6518c1c7711ef1fdbe925b3c5c71e62910374e3e/research/object_detection/eval_util.py#L199)

   If I read the code correctly, you'd be evaluating the model with the first 10k images (not randomized) each time.  In other words, the last 80k images are not used at all.

3. `eval_config.num_examples` translates to 'number of bacthes per epoch, and ' `eval_config.max_evals` to 'number of evaluation epochs'.

   - [max_number_of_evaluations](https://github.com/tensorflow/models/blob/6518c1c7711ef1fdbe925b3c5c71e62910374e3e/research/object_detection/legacy/evaluator.py#L270)
   - [checking number of evaluation epochs](https://github.com/tensorflow/models/blob/6518c1c7711ef1fdbe925b3c5c71e62910374e3e/research/object_detection/eval_util.py#L430)
