### ISSUE TITLE
The training consume all my memory

### ISSUE THREAD

**Issue by xzGithu** [jkjung-avt/hand-detection-tutorial#23]
HI.
Sorry to trouble you. I trained my hand model on a jetson nano machine and use the data of egohands, I set the batch size to 2, and I saw it eaten all my 4GB memory and 4GB swap, after a while the training steps hangs, so where can I set the limit use of the memory when use the train.py .

**Comment by jkjung-avt** [comment]
First, Jetson Nano is meant for inference only (not for training).  It's not recommended that you train the hand detector on Jetson Nano.

In case you insist on doing it, take a look at this: https://stackoverflow.com/a/34200194/7596504.  You could read tensorflow object detection API source code and find the code piece which creates the Session, and just add the gpu_options to try to limit amount GPU memory used by tensorflow.

**Comment by xzGithu** [comment]
I will read the API carefully. So why it use all my host memory? just because my lack of GPU memory

**Comment by jkjung-avt** [comment]
Jetson Nano only has 4GB of RAM.  It shared between GPU and CPU.  And GPU cannot use swap as part of its memory.

**Comment by xzGithu** [comment]
Thanks, I see that. I will try to adjust the session config to limit memory.
