### ISSUE TITLE
3.Run the installation script. Make sure the last step in the script

### ISSUE THREAD

**Issue by Ndron** [jkjung-avt/hand-detection-tutorial#25]
### Setup
3.Run the installation script. Make sure the last step in the script, Running model_builder_test.py, finishes without error, before continuing on.

$ ./install.sh
I got error

`python: can't open file '/home/andrei/hand-detection-tutorial-master/models/research/object_detection/builders/model_builder_test.py': [Errno 2] No such file or directory`

And there is really no such file , where i can find/get it?

**Comment by jkjung-avt** [comment]
Here is the file: https://github.com/tensorflow/models/blob/6518c1c7711ef1fdbe925b3c5c71e62910374e3e/research/object_detection/builders/matcher_builder_test.py

Note that I'm using the "6518c1c" snapshot of tensorflow object detection API (not the latest version) in this repository.
