### ISSUE TITLE
Shuffle buffer filled.

### ISSUE THREAD

**Issue by sudo-wang** [jkjung-avt/hand-detection-tutorial#28]
Hi, @jkjung-avt 
Thanks for your work! It helps me a lot.
I followed your tutorial to train ssd_mobilenet_v1 on KITTI dataset.
When I run ./train.sh ssd_mobilenet_v1_kitti, it did not succeed.
The log shows: 
INFO:tensorflow:Saving checkpoints for 0 into ssd_mobilenet_v1_kitti/model.ckpt.
I0330 12:04:13.290106 547919339536 basic_session_run_hooks.py:606] Saving checkpoints for 0 into ssd_mobilenet_v1_kitti/model.ckpt.
**2020-03-30 12:07:07.154592: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:145] Filling up shuffle buffer (this may take a while): 653 of 2048
2020-03-30 12:07:17.200949: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:145] Filling up shuffle buffer (this may take a while): 1245 of 2048
2020-03-30 12:07:27.171252: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:145] Filling up shuffle buffer (this may take a while): 1858 of 2048
2020-03-30 12:07:30.213396: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:195] Shuffle buffer filled.**
./train.sh:  60: 11880 killed              PYTHONPATH=`pwd`/models/research:`pwd`/models/research/slim python3 ./models/research/object_detection/model_main.py --pipeline_config_path=${PIPELINE_CONFIG_PATH} --model_dir=${MODEL_DIR} --num_train_steps=${NUM_TRAIN_STEPS} --sample_1_of_n_eval_samples=1 --alsologtostderr

I think it was caused by shuffle buffer size, i am not really sure. Help me!!
Please give my some hints for modification, Sincere thanks for you!

**Comment by jkjung-avt** [comment]
You could try to decrease "shuffle_buffer_size" in your config file.  The default value is [2048](https://github.com/tensorflow/models/blob/6518c1c7711ef1fdbe925b3c5c71e62910374e3e/research/object_detection/protos/input_reader.proto#L35).  Example:

```
train_input_reader: {
  tf_record_input_reader {
    input_path: "data/egohands_train.tfrecord"
  }
  label_map_path: "data/egohands_label_map.pbtxt"
  shuffle_buffer_size: 1024
}
```

**Comment by sudo-wang** [comment]
Hi, @jkjung-avt
Many thanks for your help!
I will try it.
