### ISSUE TITLE
How can I view the output log of the training

### ISSUE THREAD

**Issue by sudo-wang** [jkjung-avt/hand-detection-tutorial#29]
Hi, @jkjung-avt 
Thanks for your work! It helps me a lot.
I trained the model on the kitti dataset, but the accuracy is a little low. I want to find out the reason. Could you please tell me where the training process and intermediate results, such as loss?

**Console output：**(I think AP is too low.)
creating index...
index created!
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=26.29s).
Accumulating evaluation results...
DONE (t=3.02s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.227
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.455
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.197
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.085
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.186
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.439
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.207
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.341
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.369
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.182
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.331
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.574

**Comment by jkjung-avt** [comment]
I think the best way is to use tensorboard to monitor training progress.  I have described how to do that in the README.md.  Otherwise, please learn how to use tensorboard from google documentation or other resources.

**Comment by sudo-wang** [comment]
@jkjung-avt Thanks a lot
I found this error. This is the output of the training process
Is this the pre-trained model load failure? How to fix it?
The log is:
Instructions for updating:
Use `tf.data.Dataset.batch(..., drop_remainder=True)`.
WARNING:root:Variable [BoxPredictor_0/ClassPredictor/biases] is available in checkpoint, but has an incompatible shape with model variable.
WARNING:root:Variable [BoxPredictor_0/ClassPredictor/weights] is available in checkpoint, but has an incompatible shape with model variable.
WARNING:root:Variable [BoxPredictor_1/ClassPredictor/biases] is available in checkpoint, but has an incompatible shape with model variable.
WARNING:root:Variable [BoxPredictor_1/ClassPredictor/weights] is available in checkpoint, but has an incompatible shape with model variable.
WARNING:root:Variable [BoxPredictor_2/ClassPredictor/biases] is available in checkpoint, but has an incompatible shape with model variable.
WARNING:root:Variable [BoxPredictor_2/ClassPredictor/weights] is available in checkpoint, but has an incompatible shape with model variable.
WARNING:root:Variable [BoxPredictor_3/ClassPredictor/biases] is available in checkpoint, but has an incompatible shape with model variable.
WARNING:root:Variable [BoxPredictor_3/ClassPredictor/weights] is available in checkpoint, but has an incompatible shape with model variable.
WARNING:root:Variable [BoxPredictor_4/ClassPredictor/biases] is available in checkpoint, but has an incompatible shape with model variable.
WARNING:root:Variable [BoxPredictor_4/ClassPredictor/weights] is available in checkpoint, but has an incompatible shape with model variable.
WARNING:root:Variable [BoxPredictor_5/ClassPredictor/biases] is available in checkpoint, but has an incompatible shape with model variable.
WARNING:root:Variable [BoxPredictor_5/ClassPredictor/weights] is available in checkpoint, but has an incompatible shape with model variable.
WARNING:root:Variable [global_step] is not available in checkpoint

**Comment by jkjung-avt** [comment]
These warnings are normal.

The pre-trained SSD COCO model has 80 (or 90) classes of objects, which differs from your custom SSD model.  So, those "BoxPredictor_?/ClassPredictor" have different output shapes and have to be trained from scratch (cannot use pre-trained weights).

**Comment by abdou31** [comment]
Is it possible to use transfer learning?

**Comment by jkjung-avt** [comment]
We are indeed using transfer learning here.  It's only the last layers which need to be initialized from scratch.

**Comment by abdou31** [comment]
Yes, I think that transfer learning give access to use a pre-trained model by replacing the fully connected layer with a new another layer ( with a number of units that corresponding to the number of classes ).
