### ISSUE TITLE
Trouble converting retrained SSD Mobilenet v2 model to TensorRT engine

### ISSUE THREAD

**Issue by jchryssanthacopoulos** [jkjung-avt/hand-detection-tutorial#30]
Hi, this issue is pretty similar to https://github.com/jkjung-avt/hand-detection-tutorial/issues/24.

I retrained ssd_mobilenet_v2_coco on a custom dataset and would like to use it on my Jetson Nano. I'm using two classes. I used tensorflow 1.14 to retrain the model from the checkpoint using the Object Detection API at this commit: https://github.com/tensorflow/models/tree/adc01cd76ae0d9d3b2e8dde3ec6bf4086f7da046. That worked successfully, and I have a frozen_inference_graph.pb.

I'm trying to use your script to build a TensorRT engine. I'm using the same settings for "min_size", "max_size", and "input_order" as you use for ssd_mobilenet_v2_coco. When I run it, I also get the error:

[TensorRT] ERROR: UffParser: Validator error: FeatureExtractor/MobilenetV2/layer_19_2_Conv2d_4_3x3_s2_256/BatchNorm/FusedBatchNormV3: Unsupported operation _FusedBatchNormV3
num layers= 0
[TensorRT] ERROR: Network must have at least one output
Traceback (most recent call last):
  File "build_engine.py", line 233, in <module>
    main()
  File "build_engine.py", line 227, in main
    buf = engine.serialize()
AttributeError: 'NoneType' object has no attribute 'serialize'

I see that you recommended adding 1 to "num_classes", or changing "input_order", but neither of those worked for me. Also, I didn't retrain the model with a background class, only my two custom classes, so I'm not sure changing "num_classes" makes sense.

These are the versions running on the Nano:

tensorflow: 1.14
tensorrt: 6.0.1.10
uff: 0.6.5

I know you suggest running earlier versions of tensorflow and the Object Detection API, but as I was getting the same error when running "ssd_tensorrt.py" as part of the jetbot repo, I thought something else might be happening here. Also, I'd ideally not tie myself to older versions in this way.

Thanks for your help.

**Comment by jkjung-avt** [comment]
1. For the problem of "FusedBatchNormV3", please refer to: https://github.com/jkjung-avt/tensorrt_demos/issues/76#issuecomment-607879831

2. Be sure to add 1 to "num_classes".

**Comment by jchryssanthacopoulos** [comment]
Awesome, thank you. I included your patch for converting "FusedBatchNormV3" to "FusedBatchNorm", and now I get

[TensorRT] ERROR: UffParser: Validator error: Cast: Unsupported operation _Cast

Any thoughts?

**Comment by jkjung-avt** [comment]
"Cast" ops in a tensorflow graph are only doing data type conversion (e.g. int64 -> float32).  Since TensorRT would manage data types (FP16 <-> FP32, etc.) by itself, you don't need to keep those Cast ops in the graph when building TensorRT engines.

I think you could just remove all "Cast" ops by using graphsurgeon's "forward_inputs()" API.  Reference: https://github.com/jkjung-avt/tensorrt_demos/blob/master/ssd/build_engine.py#L93

**Comment by jchryssanthacopoulos** [comment]
Interesting, thanks. I'm already using that `forward_inputs()` function in `add_plugin`, but you're saying I need to use it explicitly on some of these cast operations as well?

**Comment by jkjung-avt** [comment]
I'm not 100% sure whether this would solve your problem.  But I definitely think it's worth trying to do forward_inputs() for all Cast nodes in your graph.  (I think forward_inputs() would remove a Cast node and re-connect its input node and output node.)

**Comment by rasheeddo** [comment]
> 1. For the problem of "FusedBatchNormV3", please refer to: [jkjung-avt/tensorrt_demos#76 (comment)](https://github.com/jkjung-avt/tensorrt_demos/issues/76#issuecomment-607879831)
> 2. Be sure to add 1 to "num_classes".

The first one works for me thanks! But I need to set num_classes to 2 similar to egohands example, other wise it will throw this error to me 
`python3: nmsPlugin.cpp:140: virtual void nvinfer1::plugin::DetectionOutput::configureWithFormat(const nvinfer1::Dims*, int, const nvinfer1::Dims*, int, nvinfer1::DataType, nvinfer1::PluginFormat, int): Assertion 'numPriors * param.numClasses == inputDims[param.inputOrder[1]].d[0]' failed.
Aborted (core dumped)`

 and cannot generate TRT_.bin file

**Comment by EriqueSouza** [comment]
Hi @jchryssanthacopoulos , I am trying to retrain ssd_mobilenet_v2_coco but I don't know how I do this. Can you help me with it?
