### ISSUE TITLE
how to see several images

### ISSUE THREAD

**Issue by gpqls** [jkjung-avt/hand-detection-tutorial#34]
https://drive.google.com/file/d/1--NDacaHTg9zh0CSt1mzpuGEUg_sqLV0/view?usp=sharing

When I run the ./eva.shl and look at the tensorboard, there is only one image like image in link.
I want to detect several images. What should be my directory configuration?

https://drive.google.com/file/d/15mNcnYm4gWyLA9PTPeyYOWUReKYQzZfn/view?usp=sharing
The above links are my directory configuration and images. Only the first image is detected.

**Comment by jkjung-avt** [comment]
I'm not sure.  Could you try to modify [this line of code in model_lib.py](https://github.com/tensorflow/models/blob/6518c1c7711ef1fdbe925b3c5c71e62910374e3e/research/object_detection/model_lib.py#L372) to the following?  (You could replace 64 with a larger number if you'd like.)

```
        img_summary = tf.summary.image('Detections_Left_Groundtruth_Right',
                                       detection_and_groundtruth,
                                       max_outputs=64)
```

Reference: https://www.tensorflow.org/api_docs/python/tf/compat/v1/summary/image

Let me know if it works.

**Comment by gpqls** [comment]
It works the same as before... Thanks.

**Comment by jkjung-avt** [comment]
I see.  I guess we need to modify the code so that it saves all evaluated images (into a big batch) and calls tf.summary.imag() with those altogether.  It would probably require a lot of code changes.

From what I can see, the original tensorflow object detection API code simply does not support that.  I guess you could file this as a feature request to tensorflow/models.

**Comment by gpqls** [comment]
Thank you for your reply!!

**Comment by gpqls** [comment]
https://drive.google.com/file/d/18kzG7vUzHhlSB9hRI_0Z6Voc2j9z3WLM/view?usp=sharing

Hi, I could see these results like you when I ran the 'eval.sh'.
But I don't know what this means. 
I know about "IoU", I don't know "0.50:0.95", "area", "maxDets"'s mean.

**Comment by jkjung-avt** [comment]
https://jkjung-avt.github.io/trt-detection-map/
