### ISSUE TITLE
Training with background images

### ISSUE THREAD

**Issue by PiyalGeorge** [jkjung-avt/hand-detection-tutorial#36]
Hi @jkjung-avt ,

I have trained a model in mobilenet-ssd-v2 model in Tensorflow(less than version 2.0) for detecting "mobile-phone in hand". I trained with images having 'mobile-phones in hand'. Threshold is set to 7. So if hold a mobile-phone in my hand it will detect. This scenario is working, but the issue is when i hold some other objects(like cup, pen) in my hand, that also is getting detected. That is, i'm getting wrong detection. How can i reduce this wrong detection? Will training with other images like - image having hand held cup, book, etc without specifying label in xml - help to avoid these wrong detection?

I have gone through some issues in github regarding this, but still i'm not getting a clarity on this, that's why i come to you. Hope you will help me to get a clarity on this. Kindly help me.

**Comment by jkjung-avt** [comment]
> Will training with other images like - image having hand held cup, book, etc without specifying label in xml - help to avoid these wrong detection?

Yes.

**Comment by PiyalGeorge** [comment]
Thanks for the reply, @jkjung-avt  . One more doubt on same topic- This is how my annotation for an image with mobile-in-hand looks like:
```
<annotation>
	<folder>cropped</folder>
	<filename>2.jpg</filename>
	<path>/home/2.jpg</path>
	<source>
		<database>Unknown</database>
	</source>
	<size>
		<width>500</width>
		<height>500</height>
		<depth>3</depth>
	</size>
	<segmented>0</segmented>
	<object>
		<name>mobileinhand</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>247</xmin>
			<ymin>266</ymin>
			<xmax>296</xmax>
			<ymax>304</ymax>
		</bndbox>
	</object>
</annotation>
```
So, Can i include new images for '**learning background only**' (eg: images having cup-in-hand kinda) with xml like below(**With no object** specified in xml), Is this method possible:

```
<annotation>
	<folder>cropped</folder>
	<filename>2.jpg</filename>
	<path>/home/2.jpg</path>
	<source>
		<database>Unknown</database>
	</source>
	<size>
		<width>500</width>
		<height>500</height>
		<depth>3</depth>
	</size>
	<segmented>0</segmented>
</annotation>
```

**Comment by jkjung-avt** [comment]
I think setting a good value of [min_negatives_per_image](https://github.com/tensorflow/models/blob/6518c1c7711ef1fdbe925b3c5c71e62910374e3e/research/object_detection/samples/configs/ssd_mobilenet_v2_coco.config#L122) in your config should do the trick.

You could refer to this comment in the object detection API source code ([core/losses.py](https://github.com/tensorflow/models/blob/6518c1c7711ef1fdbe925b3c5c71e62910374e3e/research/object_detection/core/losses.py#L482)):

>         min_negatives_per_image: minimum number of negative anchors to sample for
>         a given image. Setting this to a positive number allows sampling
>         negatives in an image without any positive anchors and thus not biased
>         towards at least one detection per image.
