### ISSUE TITLE
Retraining Custom MobilenetV2-fn and use on TensorRT

### ISSUE THREAD

**Issue by 1208overlord** [jkjung-avt/hand-detection-tutorial#38]
Hello, I trained custom mobilenetv2_fn model with 6 classes on Tensorflow 1.15 version.
And then, I converted to pb file.
But when building TensorRT model, I have the following error.

Using output node NMS
Converting to UFF graph
Warning: No conversion function registered for layer: NMS_TRT yet.
Converting NMS as custom op: NMS_TRT
Warning: No conversion function registered for layer: FlattenConcat_TRT yet.
Converting concat_box_conf as custom op: FlattenConcat_TRT
Warning: No conversion function registered for layer: Unpack yet.
Converting Preprocessor/unstack as custom op: Unpack
Warning: No conversion function registered for layer: GridAnchor_TRT yet.
Converting GridAnchor as custom op: GridAnchor_TRT
Warning: No conversion function registered for layer: FlattenConcat_TRT yet.
Converting concat_box_loc as custom op: FlattenConcat_TRT
DEBUG [/usr/lib/python3.6/dist-packages/uff/converters/tensorflow/converter.py:96] Marking ['NMS'] as outputs
No. nodes: 612
UFF Output written to ssd_mobilenet_v2_coco_2018_03_29/frozen_inference_graph_1.uff
[TensorRT] ERROR: UffParser: Validator error: Preprocessor/unstack: Unsupported operation _Unpack
Building TensorRT engine, this may take a few minutes...
[TensorRT] ERROR: Network must have at least one output
Traceback (most recent call last):
File "main.py", line 371, in
buf = trt_engine.serialize()
AttributeError: 'NoneType' object has no attribute 'serialize'

Please help me how to fix it.
I attach pb file and python file I used.
I will expect good news ASAP.

https://drive.google.com/drive/folders/1DrCFP3T0mFSm1GNzRp8aude-Ona6SoMz?usp=sharing

**Comment by jkjung-avt** [comment]
> [TensorRT] ERROR: UffParser: Validator error: Preprocessor/unstack: Unsupported operation _Unpack

This probably means your tensorflow graph contains "Unpack" nodes ([reference](https://www.tensorflow.org/api_docs/python/tf/raw_ops/Unpack?hl=pl)) which are not supported by TensorRT.  In fact, TensorRT does not care about the exact shape of the tensors, so you could just remove the "Unpack" nodes.

Refer to:

https://github.com/jkjung-avt/tensorrt_demos/blob/master/ssd/build_engine.py#L156-L157

You could add the following code to remove "Unpack" nodes in the graph.

```
    all_identity_nodes = graph.find_nodes_by_op('Unpack')
    graph.forward_inputs(all_identity_nodes)
```

**Comment by 1208overlord** [comment]
Thank you for your reply.
And then, I have this error.

[TensorRT] ERROR: UffParser: Validator error: FeatureExtractor/MobilenetV2/Cast_2: Unsupported operation _Cast

What is the reason of this?
After converting to pb file, I successfully inferenced it.
It says that I correctly converted to pb file?
But when building TensorRT, some troubles exist.
Please help me.

**Comment by jkjung-avt** [comment]
Please refer to this pull request which fixes "Unsupported operation _Cast" in the "Input" nodes: https://github.com/jkjung-avt/tensorrt_demos/pull/115

I think you need to use graphsurgeon to remove/replace the "Cast_2" node in the "FeatureExtractor" as well.  I don't have time to investigate this further.  Hopefully you'll be able to solve the problem by referencing this hint.

**Comment by 1208overlord** [comment]
Sorry, but could you please help me?
If you want, I can pay for your time for me.

**Comment by 1208overlord** [comment]
Hello
I downloaded pretrained checkpoint file and pb file from google.
And then, after I convert that checkpoint file to pb in my own according to guide and compare with the downloaded pb file, the structure is different.
What is wrong?
Could you please help me?
I am studying TensorRT to work on big project for some company.
Please help.
Thank you.

**Comment by 1208overlord** [comment]
Are you busy?

**Comment by jkjung-avt** [comment]
> Are you busy?

Yes.  I have a full-time job.

**Comment by 1208overlord** [comment]
Could you please give me some help?
And what job do you work?
Can I work for you?

**Comment by 1208overlord** [comment]
Hello, please help with only one issue.

If there exists "Unsupported operation **", the following is the best way to resolve?

    all_identity_nodes = graph.find_nodes_by_op('Unpack')
    graph.forward_inputs(all_identity_nodes)

    all_identity_nodes = graph.find_nodes_by_op('Cast')
    graph.forward_inputs(all_identity_nodes)

    all_identity_nodes = graph.find_nodes_by_op('Fill')
    graph.forward_inputs(all_identity_nodes)
	
    all_identity_nodes = graph.find_nodes_by_op('Ceil')
    graph.forward_inputs(all_identity_nodes)

**Comment by jkjung-avt** [comment]
> If there exists "Unsupported operation **", the following is the best way to resolve?

**NO.**  You need to understand what functions those ops do.  For some of them, you could remove the nodes directly.  However, for the rest, you'll need to replace them with something TensorRT could handle (either directly supported ops or plugins).

**Comment by 1208overlord** [comment]
Could you please help with my models?
I want to do it really.

**Comment by 1208overlord** [comment]
ERROR: UffParser: Validator error: FeatureExtractor/MobilenetV2/zeros: Unsupported operation _Fill

In this case, can I remove it directly?

if remove directly, the following error:
 ERROR: UffParser: Parser error: FeatureExtractor/MobilenetV2/Ceil: Unsupported unary op ceil

If remove this, too,
ERROR: UffParser: Parser error: FeatureExtractor/MobilenetV2/Conv/Conv2D: Order size is not matching the number dimensions of TensorRT

Please help how to fix this..
I hope you help me.

**Comment by 1208overlord** [comment]
Perhaps, my config.py is wrong?
[main_custom.zip](https://github.com/jkjung-avt/hand-detection-tutorial/files/5450976/main_custom.zip)

**Comment by 1208overlord** [comment]
Hello, could you please introduce some jobs?
[yevhenii.pdf](https://github.com/jkjung-avt/hand-detection-tutorial/files/5455387/yevhenii.pdf)
