### ISSUE TITLE
About model

### ISSUE THREAD

**Issue by miooooooooooo** [jkjung-avt/hand-detection-tutorial#39]
Thanks for you great project, can you share your model "ssdlite_mobilenet_v2_egohands" to my google account "a445061450@gmail.com",Thank you.

**Comment by jkjung-avt** [comment]
@miooooooooooo  The trained model is too large to be sent through email.  Please provide a folder/link to your Google Drive (or something similar) so that I could upload the file.

**Comment by miooooooooooo** [comment]
"https://drive.google.com/drive/folders/1fkQPCGyUMxnToB2P1fitpWLbPAjqYZRD?usp=sharing". Is this link available?

**Comment by jkjung-avt** [comment]
Closing per https://github.com/jkjung-avt/hand-detection-tutorial/issues/21#issuecomment-740338263
