### ISSUE TITLE
Keeps running on CPU even with CUDA_VISIBLE_DEVICES=0 ./train.sh ssd_mobilenet_v1_egohands

### ISSUE THREAD

**Issue by maky-hnou** [jkjung-avt/hand-detection-tutorial#9]
When I use `CUDA_VISIBLE_DEVICES=0 ./train.sh ssd_mobilenet_v1_egohands` normally it should run on the **GPU**, but it keeps running on the **CPU**. Although I have *tensorflow-gpu* and *tensorflow-cpu* both installed.

**Comment by jkjung-avt** [comment]
TensorFlow 'models' library uses  [tf.estimator.Estimator](https://www.tensorflow.org/api_docs/python/tf/estimator/Estimator) to do the training/evaluation.  I googled and didn't seem to find a documented way to ask the Estimator to place the training session on a GPU.

Doing it in a hacky way, maybe you could try to wrap the [main()](https://github.com/tensorflow/models/blob/6518c1c7711ef1fdbe925b3c5c71e62910374e3e/research/object_detection/model_main.py#L52) function in [models/research/object_detection/model_main.py](https://github.com/tensorflow/models/blob/6518c1c7711ef1fdbe925b3c5c71e62910374e3e/research/object_detection/model_main.py) with `with tf.device('/device:GPU:0'):` to force device placement on GPU?

```python
def main(unused_argv):
  with tf.device('/device:GPU:0'):
    ...... # original code
```

Let me know if it works or not.

**Comment by maky-hnou** [comment]
@jkjung-avt, unfortunately, it didn't work.
Thank you for your help.

**Comment by jkjung-avt** [comment]
How about adding a train_distribute strategy which specifies the gpu as the device?  E.g. modify [this line](https://github.com/tensorflow/models/blob/6518c1c7711ef1fdbe925b3c5c71e62910374e3e/research/object_detection/model_main.py#L55) in model_main.py.

```
    strategy = tf.contrib.distribute.OneDeviceStrategy(device='/gpu:0')
    config = tf.estimator.RunConfig(model_dir=FLAGS.model_dir, train_distribute=strategy)
```

**Comment by jkjung-avt** [comment]
Did the 'train_distribute' setting help to solve your problem?

**Comment by maky-hnou** [comment]
@jkjung-avt , sorry for my late reply. Yes it solved the problem.
Thank you a lot.

**Comment by Ndron** [comment]
After this manipulations GPU utilization still 0 , training on CPU.
Instaled only tensorflow-gpu==1.14
comand:
CUDA_VISIBLE_DEVICES=0 sh train.sh ssd_mobilenet_v1_egohands

**Comment by jkjung-avt** [comment]
I just tested the code with tensorflow-1.14.0 (built from source by myself, with CUDA enabled).  It worked as expected.  GPU (RTX-2080 Ti) utilization was hovering around 55~60% when I tried to train "ssd_mobilenet_v1_egohands".
